server:
  port: 8189
  servlet:
    context-path: /app
spring:
  datasource:
    spring:
      datasource:
        initialization-mode: always
    driver-class-name: org.hsqldb.jdbc.JDBCDriver
    url: jdbc:hsqldb:file:opt/db/testdb; ifexists = true"
    username: eg
    password: 123
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.HSQLDialect
